default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV["MYSQL_DB_USERNAME"] %>
  password: <%= ENV["MYSQL_DB_PASSWORD"] %>

development:
  <<: *default
  database: testapp_dev

test:
  <<: *default
  database: testapp_test

production:
  <<: *default
  database: testapp_production
